[workspace]

[package]
name = "bridge_cell"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only WITH LicenseRef-Myrmic-exception-1.0"
publish = false

[package.metadata.myrmic]
heap_size = 8_000

[lib]
crate-type = ["rlib"]

[dependencies]
myrmic-sdk = { path = "../../../../../sdk/myrmic-sdk" }
