//! Modem firmware for ESP32 chips — the reference `esp-firmware` binary.
//!
//! Everything this firmware does lives in [`esp_firmware`]; what is left here
//! is the crate-level scaffolding a binary must own (`no_std`/`no_main`, the
//! chip features, the build script) and the Signal Layer pipeline wiring, which
//! is code-generated at build time and so cannot live in the library.

#![no_std]
#![no_main]

// Imports required for pipeline codegen output
#[cfg(feature = "pipeline")]
use esp_firmware::embassy_executor::Spawner;
#[cfg(feature = "pipeline")]
use esp_firmware::esp_hal::peripherals::Peripherals;

// The pipeline module generated by build.rs from a board manifest + pipeline
// YAML. The macro gates it on the `pipeline` feature and routes the generated
// crate paths through esp-firmware's re-exports, so this crate needs no direct
// dependency on the infrastructure crates.
esp_firmware::pipeline!();

#[cfg(not(feature = "pipeline"))]
#[esp_firmware::main]
async fn setup() {}

// With a pipeline, the board claims its own hardware first: the codegen-emitted
// macros move the bus peripherals named by the board manifest and the pins it
// reserves out of `Peripherals`, and only what is left is offered to the cell.
// The pipeline's slots go into the board's registries, which `start` hands to
// the runtime; the generated `setup_*_registry` entry points are not used.
#[cfg(feature = "pipeline")]
#[esp_firmware::main]
async fn setup(mut peripherals: Peripherals, spawner: Spawner) {
    let board_peripherals = pipeline_board_peripherals!(peripherals);
    let pins = pipeline_pins!(peripherals);

    let mut board = esp_firmware::board!(peripherals, pins = pins);
    pipeline_config::register_taps(board.taps()).expect("pipeline taps fit the registry");
    pipeline_config::register_outlets(board.outlets()).expect("pipeline outlets fit the registry");
    pipeline_config::spawn_sources(&spawner, board_peripherals);
    esp_firmware::start(board, spawner);
}
