//! Modem Firmware for ESP32 SOCs
#![no_std]
#![no_main]

pub mod network;
#[cfg(feature = "pipeline")]
#[rustfmt::skip] // generated artifact — never format, never require the file to exist
mod pipeline_config;
#[cfg(feature = "stack-hwm")]
mod stack_hwm;
mod wasm;

use core::ffi::c_void;

use esp_common::{esp_bootloader_esp_idf, esp_println, esp_radio_rtos_driver};

use esp_common::esp_watchdog::{liveness, report, watchdog};

use embassy_executor::Spawner;
use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::channel::{Channel, Receiver, Sender};
use esp_common::esp_mmu::mmu_from_peripherals;
#[cfg(feature = "ble")]
use esp_common::esp_nimble_host::{self, HostTransport};
#[cfg(feature = "ble")]
use esp_common::esp_radio::ble::controller::BleConnector;
use esp_common::esp_storage::FlashStorage;
#[cfg(feature = "ble")]
use esp_hal::peripherals::BT;
use esp_hal::peripherals::WIFI;
use esp_hal::rtc_cntl::Rtc;
use esp_hal::timer::timg::TimerGroup;
use esp_rtos::CurrentThreadHandle;
use esp_rtos::embassy::Executor;
use static_cell::StaticCell;
#[cfg(feature = "ble")]
use wasm_runtime::async_request::ble_manager_task;
use wasm_runtime::async_request::timer_manager_task;
use wasm_runtime::async_request::zenoh::{Requests, RequestsReceiver, Responses, ResponsesSender};
use wasm_runtime::async_request::{DbClientRequest, DbClientResponse};
use wasm_storage::WasmStorage;

// `pins_from_peripherals!` expands a bare `Pins` identifier, so it needs the import
// in scope. The codegen-emitted `pipeline_pins!` uses the fully-qualified
// `wasm_runtime::Pins` path itself, so the import is dead when the pipeline is on.
#[cfg(not(feature = "pipeline"))]
use wasm_runtime::Pins;

use wasm_runtime::{WasmTransfer, from_thread_arg, into_thread_arg};

esp_bootloader_esp_idf::esp_app_desc!();

// AOT flash `PartitionLayout` generated by build.rs from the optional `partitions.toml`.
// Defines `PARTITION_LAYOUT`; passed to `WasmStorage::new` below.
include!(concat!(env!("OUT_DIR"), "/partition_layout.rs"));

/// HCI transport thread — bridges BLE controller ↔ Nimble host.
/// Must run at highest priority so C2H HCI packets don't leak memory.
#[cfg(feature = "ble")]
extern "C" fn ble_transport_thread(_: *mut c_void) {
    static EXECUTOR: StaticCell<Executor> = StaticCell::new();
    let executor = EXECUTOR.init(Executor::new());

    executor.run(|spawner| {
        // SAFETY: the BT peripheral is used exclusively by this HCI transport thread;
        // nothing else steals or holds it, so there is no aliasing.
        let bluetooth = unsafe { BT::steal() };
        let controller_connector = BleConnector::new(bluetooth, Default::default()).unwrap();
        let host_transport = HostTransport::new(controller_connector);
        spawner.spawn(ble_transport_tx().unwrap());
        spawner.spawn(ble_transport_rx(host_transport).unwrap());
    });
}

#[cfg(feature = "ble")]
#[embassy_executor::task]
async fn ble_transport_tx() {
    esp_nimble_host::transport_task_tx().await;
}

#[cfg(feature = "ble")]
#[embassy_executor::task]
async fn ble_transport_rx(transport: HostTransport) {
    esp_nimble_host::transport_task_rx(transport).await;
}

/// Network-service thread stack. The zenoh/db poll chains are the deepest in the
/// firmware; running them on an owned, fixed-size stack makes that demand a
/// declared budget instead of a claim on whatever RAM `.bss` happens to leave the
/// main stack.
///
/// Sizing: at 28 KB the cell-start chain overflowed the bottom of this stack by
/// ~768 B and overwrote the statics below it (#1323) — the RTOS stack checks only
/// run at context switches, so the overflow was silent until the corrupted state
/// crashed the WiFi driver. There is no high-water-mark instrumentation for this
/// task (`stack-hwm` paints only the main linker stack), so this budget rests on
/// the HIL suite passing, not on a measured peak. Don't shrink it without adding
/// that measurement first.
const NET_STACK: usize = 40 * 1024;

/// Everything [`net_service_thread`] hands to `network::start_service`, passed
/// via [`into_thread_arg`].
struct NetServiceArgs {
    wifi: WIFI<'static>,
    wasm_transfer: Sender<'static, CriticalSectionRawMutex, WasmTransfer, 1>,
    db_requests: Receiver<'static, CriticalSectionRawMutex, DbClientRequest, 1>,
    db_responses: Sender<'static, CriticalSectionRawMutex, DbClientResponse, 1>,
    zenoh_requests: RequestsReceiver,
    zenoh_responses: ResponsesSender,
}

/// Network service thread — runs the WiFi/zenoh/db executor on its own
/// [`NET_STACK`]-sized stack instead of the leftover-RAM main stack.
extern "C" fn net_service_thread(arg: *mut c_void) {
    static EXECUTOR: StaticCell<Executor> = StaticCell::new();

    // SAFETY: `arg` is the `into_thread_arg` of the `NetServiceArgs` built in
    // `main`; the thread runs once and takes ownership.
    let args: NetServiceArgs = unsafe { from_thread_arg(arg) };

    let executor = EXECUTOR.init(Executor::new());
    executor.run(|spawner| {
        network::start_service(
            spawner,
            args.wifi,
            args.wasm_transfer,
            args.db_requests,
            args.db_responses,
            args.zenoh_requests,
            args.zenoh_responses,
        );
    });
}

/// Task wrapper for the watchdog feeder. Tasks stay in the binary so the
/// embassy-executor version remains a firmware-side choice.
#[embassy_executor::task]
async fn watchdog_feeder(feed: fn()) {
    liveness::watchdog_feeder(feed).await;
}

/// Task wrapper for the stats heartbeat — the sole required liveness task.
#[embassy_executor::task]
async fn stats() {
    #[cfg(feature = "wdt-selftest")]
    let wedge_mode = Some(wasm_runtime::wdt_selftest_wedge_mode as fn() -> u8);
    #[cfg(not(feature = "wdt-selftest"))]
    let wedge_mode = None;

    #[cfg(feature = "stack-hwm")]
    let stack_hwm = Some(stack_hwm::stack_high_water_mark as fn() -> usize);
    #[cfg(not(feature = "stack-hwm"))]
    let stack_hwm = None;

    liveness::heartbeat(wedge_mode, stack_hwm).await;
}

#[esp_rtos::main]
async fn main(main_spawner: Spawner) {
    // Plain statics so the compiler enforces `Sync` on the channels — they are
    // shared across the main and net-service executor threads, and a cell type
    // (unconditionally `Sync`) would skip that check.
    static WASM_TRANSFER: Channel<CriticalSectionRawMutex, WasmTransfer, 1> = Channel::new();
    static DB_REQUESTS: Channel<CriticalSectionRawMutex, DbClientRequest, 1> = Channel::new();
    static DB_RESPONSES: Channel<CriticalSectionRawMutex, DbClientResponse, 1> = Channel::new();
    static ZENOH_REQUESTS: Requests = Channel::new();
    static ZENOH_RESPONSES: Responses = Channel::new();

    // BLE task stacks. Profiled: floor ~1.5 KB, 4 KB gives 2x safety margin (was 64 KB each).
    #[cfg(feature = "ble")]
    const BLE_HCI_STACK: usize = 4 * 1024;
    #[cfg(feature = "ble")]
    const BLE_HOST_STACK: usize = 4 * 1024;

    let peripherals = esp_hal::init(esp_hal::Config::default());

    // Init the logger before the heap so `setup_heap!`'s boot memory summary
    // (region sizes + low-heap warning) reaches the console.
    esp_println::logger::init_logger_from_env();
    esp_common::esp_heap::setup_heap!(peripherals);

    log::info!("Init!");
    report::snapshot("post-init");

    // If this boot follows a watchdog reset, log it and queue the swarm
    // report (SDS Area D). Must run before `watchdog::arm` below.
    watchdog::report_boot();

    // Build the Signal Layer board peripherals from the generated config. The
    // generated `pipeline_board_peripherals!` macro moves only the bus
    // peripherals this pipeline uses (selected from the board manifest), so
    // `peripherals` stays available for everything else and the firmware names
    // no pins itself.
    #[cfg(feature = "pipeline")]
    let board = pipeline_board_peripherals!(peripherals);

    // Claim the remaining GPIO pins for the WASM runtime. The codegen-emitted
    // `pipeline_pins!` macro moves each non-reserved GPIO out of `peripherals`
    // explicitly (so the borrow checker prevents later reuse) and emits `None`
    // for pins reserved by `pipeline_board_peripherals!` — no partial-move
    // conflict because the macro never names the reserved fields.
    #[cfg(feature = "pipeline")]
    let pins = pipeline_pins!(peripherals);
    #[cfg(not(feature = "pipeline"))]
    let pins = wasm_runtime::pins_from_peripherals!(peripherals);

    #[cfg(feature = "pipeline")]
    {
        let tap_count = pipeline_config::setup_tap_registry();
        log::info!("[tap] Registry initialised ({tap_count} taps)");
        let outlet_count = pipeline_config::setup_outlet_registry();
        log::info!("[outlet] Registry initialised ({outlet_count} outlets)");
    }

    report::snapshot("post-wiring");

    let timg0 = TimerGroup::new(peripherals.TIMG0);
    esp_rtos::start(timg0.timer0, peripherals.FROM_CPU_INTR0);

    // Spawn all required tasks (Higher number = Higher priority):
    //  Embassy Thread executor:                Priority 40 (BLE HCI transport)
    //  OS Task:                                Priority 30 (BLE Host / Nimble)
    //  OS Task (spawned by esp-radio):         Priority 29 (BLE Controller)
    //  Main Embassy Thread executor:           Priority 1 (runs wasm request handler, stats)
    //  Network Embassy Thread executor:        Priority 1 (zenoh/wifi/db on an owned
    //                                          NET_STACK-sized stack; time-sliced with main)
    //  OS Task:                                Priority 0 (runs the WAMR Runtime)

    // Set our main thread prio to 1
    CurrentThreadHandle::set_priority(CurrentThreadHandle::get(), 1);

    // Paint the unused main stack so peak usage can be measured (debug aid). Must
    // run after `esp_rtos::start` and before the deep tasks are spawned.
    #[cfg(feature = "stack-hwm")]
    stack_hwm::paint_unused_stack();

    // Spawn HCI transport (HIGH prio — must not block or C2H packets leak)
    // SAFETY: ble_transport_thread is a valid extern "C" entry point and takes no
    // argument (null arg); task_create is called once at startup.
    #[cfg(feature = "ble")]
    unsafe {
        esp_radio_rtos_driver::task_create(
            "HCI transport",
            ble_transport_thread,
            core::ptr::null_mut(),
            40,
            None,
            BLE_HCI_STACK,
        );
    }
    // Spawn BLE Host / Nimble (MID-HIGH prio)
    // SAFETY: esp_nimble_host::host_task is a valid extern "C" entry point and takes
    // no argument (null arg); task_create is called once at startup.
    #[cfg(feature = "ble")]
    unsafe {
        esp_radio_rtos_driver::task_create(
            "BLE Host",
            esp_nimble_host::host_task,
            core::ptr::null_mut(),
            30,
            None,
            BLE_HOST_STACK,
        );
    }

    // Network service (WiFi + zenoh + db) on its own executor thread: its poll
    // chains are the firmware's deepest, so they run on an owned NET_STACK-sized
    // stack instead of the leftover-RAM main stack.
    let net_args = NetServiceArgs {
        wifi: peripherals.WIFI,
        wasm_transfer: WASM_TRANSFER.sender(),
        db_requests: DB_REQUESTS.receiver(),
        db_responses: DB_RESPONSES.sender(),
        zenoh_requests: ZENOH_REQUESTS.receiver(),
        zenoh_responses: ZENOH_RESPONSES.sender(),
    };
    // SAFETY: net_service_thread is a valid extern "C" entry point; its argument
    // is an `into_thread_arg` NetServiceArgs whose ownership moves to the thread.
    unsafe {
        esp_radio_rtos_driver::task_create(
            "net service",
            net_service_thread,
            into_thread_arg(net_args),
            1,
            None,
            NET_STACK,
        );
    }
    main_spawner.spawn(
        wasm::wasm_request_handler(
            pins,
            DB_REQUESTS.sender(),
            DB_RESPONSES.receiver(),
            ZENOH_REQUESTS.sender(),
            ZENOH_RESPONSES.receiver(),
        )
        .unwrap(),
    );

    #[cfg(feature = "pipeline")]
    pipeline_config::spawn_sources(&main_spawner, board);

    main_spawner.spawn(stats().unwrap());

    // Hardware watchdogs (SDS-FEAT-2026-HWD-001): arm the staged MWDT on
    // TIMG1 + the RWDT backstop, then start the watchdog feeder that
    // feeds them while every required task proves progress. From here on, a
    // wedged runtime resets the device.
    let timg1 = TimerGroup::new(peripherals.TIMG1);
    let rtc = Rtc::new(peripherals.RTC_TIMER);
    watchdog::arm(rtc.rwdt, timg1.wdt);
    main_spawner.spawn(watchdog_feeder(watchdog::feed).unwrap());

    // Start WAMR on its own RTOS thread (LOW priority, so that it can be
    // blocked by embassy).
    let (module_queue, cell_message_queue) = wasm_runtime::start_runtime_thread(0, 25 * 1024);
    main_spawner.spawn(wasm::cell_task(cell_message_queue).unwrap());
    main_spawner.spawn(timer_manager_task().unwrap());
    #[cfg(feature = "ble")]
    main_spawner.spawn(ble_manager_task().unwrap());

    // Create WASM Storage
    let mmu = mmu_from_peripherals!(peripherals);
    let flash = FlashStorage::new(peripherals.FLASH);
    let wasm_storage = WasmStorage::new(mmu, flash, PARTITION_LAYOUT);
    // Spawn runtime handler: responsible for storage and dynamically storing/loading/unloading WASM
    // modules
    main_spawner.spawn(
        wasm::runtime_handler(wasm_storage, WASM_TRANSFER.receiver(), module_queue).unwrap(),
    );
}
