//! This crate implements the Swarm Onboarding process, as described in the Swarm documentation.
//!
//! It provides implementation for both the device and the installer sides of the onboarding process.

#![no_std]
#![deny(missing_docs)]
#![allow(async_fn_in_trait)]

use core::marker::PhantomData;

use aes_gcm::{Aes256Gcm, Key};

use elliptic_curve::rand_core::{CryptoRngCore, RngCore};

use embedded_io_async::ErrorKind;

use p256::NistP256;

use serde::{Deserialize, Serialize};

use thiserror::Error;

#[cfg(not(feature = "defmt"))]
use bitflags::bitflags;
#[cfg(feature = "defmt")]
use defmt::bitflags;

use crate::ecies::Secret;
use crate::ecies::io::{create_crypto_read_opt, create_crypto_write_opt};
use crate::io::{ReadWrapper, SerdeObj, SerdeObjError, WriteWrapper};
use crate::utils::base64;

pub use utils::BufferOverflowError;

// Brings the log-level, assert and `unwrap!` macros into crate-wide scope, the way
// the vendored `fmt` module used to. A per-module `use` would leave any module that
// forgot it silently falling back to `core::assert!` and friends.
#[macro_use]
extern crate defmt_or_log;

pub(crate) mod fmt;

pub mod bundle;
pub mod io;
pub mod pipe;
pub mod qr;
pub mod zenoh;

mod ecies;
mod utils;

/// The elliptic curve used for the onboarding process: NIST P-256 (secp256r1).
///
/// Hard-coded for now
pub type OnboardingCurveArithmetic = NistP256;

/// Represents a device which is to be or is in the process of being onboarded.
///
/// This information needs to be communicated from the device to the installer
/// before the onboarding process can begin.
///
/// The communication might happen "out of band" (e.g., via a QR code, NFC, etc.)
#[derive(Copy, Clone, Debug)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct OnboardedDevice<'a> {
    /// The credentials the device will use to authenticate and attest itself for the onboarding process.
    ///
    /// All onboarding data generated by the onboarding installer will be encrypted and using these credentials,
    /// if they contain a certificate.
    creds: DeviceCreds<'a>,
    /// The profile of the device, containing information about its capabilities and requirements.
    ///
    /// This information is used by the onboarding installer to determine what data to generate
    /// and send to the device in the onboarding bundle.
    profile: DeviceProfile<'a>,
}

impl<'a> OnboardedDevice<'a> {
    /// Create a new `OnboardedDevice` instance.
    ///
    /// # Arguments
    /// - `creds`: The device credentials.
    /// - `profile`: The device profile.
    ///
    /// # Returns
    /// - A new `OnboardedDevice` instance.
    pub const fn new(creds: DeviceCreds<'a>, profile: DeviceProfile<'a>) -> Self {
        Self { creds, profile }
    }

    /// Get the device credentials.
    pub const fn creds(&self) -> &DeviceCreds<'_> {
        &self.creds
    }

    /// Get the device profile.
    pub const fn profile(&self) -> &DeviceProfile<'_> {
        &self.profile
    }

    /// Get the device ID, if available, writing it into the provided buffer.
    ///
    /// The device ID is a UTF-8 string that uniquely identifies the device.
    ///
    /// Depending on the provided device credentials, the device ID might be the EC NistP256 public key
    /// or a simple identifier.
    ///
    /// # Arguments
    /// - `buf`: A mutable byte slice to write the device ID into.
    ///
    /// # Returns
    /// - `Ok((id, buf))`: The device ID as a UTF-8 string and the remaining buffer space.
    /// - `Err(BufferOverflowError)`: The buffer was not large enough to hold the device ID.
    pub fn device_id<'b>(
        &'b self,
        buf: &'b mut [u8],
    ) -> Result<(&'b str, &'b mut [u8]), BufferOverflowError> {
        self.creds.device_id(buf)
    }

    /// Derive the symmetric crypto key to use for encrypting the onboarding bundle and meta-data.
    ///
    /// # Arguments
    /// - `device`: The device being onboarded.
    /// - `rng`: A cryptographic random number generator.
    /// - `buf`: A buffer for temporary data storage.
    ///
    /// # Returns
    /// - `Ok((ResponseMeta, Option<Key<Aes256Gcm>>, &'a mut [u8])`: The derived meta-data, optional crypto key, and remaining buffer.
    /// - `Err(InstallerError)`: An error occurred during key derivation.
    #[allow(clippy::type_complexity)]
    pub fn derive_channel_key<'b, R>(
        &self,
        rng: &mut R,
        buf: &'b mut [u8],
    ) -> Result<(ChannelKey, InstallerMeta<'b>, &'b mut [u8]), ErrorKind>
    where
        R: CryptoRngCore,
    {
        let secret = self.new_secret(rng);
        if let Some((secret, pub_key)) = secret {
            let key = secret.compute_crypto_key(pub_key);

            let (dh_installer_pub_key, buf) = secret.extract_pub_key(buf)?;

            Ok((
                ChannelKey(Some(key)),
                InstallerMeta {
                    dh_installer_pub_key: Some(dh_installer_pub_key),
                },
                buf,
            ))
        } else {
            Ok((
                ChannelKey(None),
                InstallerMeta {
                    dh_installer_pub_key: None,
                },
                buf,
            ))
        }
    }

    /// Create a new ephemeral ECIES secret for the onboarding process, if the device supports it.
    ///
    /// # Arguments
    /// - `rng`: A cryptographic random number generator.
    /// - `device`: The device being onboarded.
    ///
    /// # Returns
    /// - `Ok(Some((Secret<OnboardingCurveArithmetic>, &'a [u8])))`: The ephemeral secret and the device's public key.
    /// - `Ok(None)`: The device does not support ECIES.
    /// - `Err(InstallerError)`: An error occurred during secret generation.
    #[allow(clippy::type_complexity)]
    pub fn new_secret<R: CryptoRngCore>(
        &self,
        rng: &mut R,
    ) -> Option<(Secret<OnboardingCurveArithmetic>, &[u8])> {
        if let DeviceCreds::PKI { .. } = self.creds() {
            Some((Secret::new_ephemeral(rng), self.creds().pub_key().unwrap()))
        } else {
            None
        }
    }
}

/// The device credentials and key used for:
/// - Deriving the `DeviceCreds` credentials used for authenticating and attesting the device to the installer.
///   These should be sent to the installer out of band (e.g., printed on a label in a QR code, via NFC, etc.)
/// - Decrypting the onboarding bundle data, if it is encrypted.
#[derive(Copy, Clone, Debug)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum DeviceKeys<'a> {
    /// The device uses a public-private key pair for channel privacy during onboarding.
    PKI {
        /// The device EC NistP256 public key.
        pub_key: &'a [u8],
        /// The device EC NistP256 private key in PKCS-8 DER format.
        priv_key: &'a [u8],
    },
    /// The device uses a simple identifier and an insecure onboarding process.
    Insecure {
        /// The device identifier.
        device_id: &'a [u8],
    },
}

impl<'a> DeviceKeys<'a> {
    /// Get the device credentials derived from these keys.
    pub const fn creds(&self) -> DeviceCreds<'a> {
        match self {
            DeviceKeys::PKI { pub_key, .. } => DeviceCreds::PKI { pub_key },
            DeviceKeys::Insecure { device_id } => DeviceCreds::Insecure { device_id },
        }
    }

    /// Derive the cryptographic key used for decrypting the onboarding bundle data.
    ///
    /// # Arguments
    /// - `device_keys`: The device keys used for deriving the cryptographic key.
    /// - `response`: The onboarding bundle metadata.
    /// - `buf`: A mutable byte slice that can be used for temporary storage.
    ///
    /// # Returns
    /// - `Ok(Some(key))`: The derived cryptographic key.
    /// - `Ok(None)`: No cryptographic key is used (e.g., for insecure devices).
    /// - `Err(e)`: An error occurred while deriving the cryptographic key.
    pub fn derive_channel_key(
        &self,
        response: &InstallerMeta<'_>,
        buf: &mut [u8],
    ) -> Result<ChannelKey, ErrorKind> {
        let secret = self.new_secret();
        if let Some(secret) = secret {
            Ok(ChannelKey(
                secret.derive_crypto_key(response.dh_installer_pub_key, buf)?,
            ))
        } else {
            Ok(ChannelKey(None))
        }
    }

    /// Create a new ECIES secret from the device keys.
    ///
    /// # Arguments
    /// - `device_keys`: The device keys used for creating the secret.
    ///
    /// # Returns
    /// - `Ok(Some(secret))`: The created ECIES secret.
    /// - `Ok(None)`: No secret can be created (e.g., for insecure devices).
    /// - `Err(e)`: An error occurred while creating the secret.
    fn new_secret(&self) -> Option<Secret<OnboardingCurveArithmetic>> {
        if let DeviceKeys::PKI {
            priv_key: our_private_key,
            ..
        } = self
        {
            Some(Secret::new_secret(our_private_key))
        } else {
            None
        }
    }
}

impl<'a> From<DeviceKeys<'a>> for DeviceCreds<'a> {
    fn from(value: DeviceKeys<'a>) -> Self {
        value.creds()
    }
}

/// The credentials the device will use to authenticate and attest itself for the onboarding process.
#[derive(Copy, Clone, Debug)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum DeviceCreds<'a> {
    /// The device uses a public-private key pair for channel privacy during onboarding.
    PKI {
        /// The device EC NistP256 public key.
        pub_key: &'a [u8],
    },
    /// Insecure credentials, containing a simple device identifier.
    Insecure {
        /// The device identifier.
        device_id: &'a [u8],
    },
}

impl DeviceCreds<'_> {
    /// Get the device ID, if available, writing it into the provided buffer.
    ///
    /// The device ID is a UTF-8 string that uniquely identifies the device.
    ///
    /// Depending on the provided device credentials, the device ID might be derived from the certificate
    /// (either from the CN attribute or from the public key)
    /// or be a simple identifier.
    ///
    /// # Arguments
    /// - `buf`: A mutable byte slice to write the device ID into.
    ///
    /// # Returns
    /// - `Ok((id, buf))`: The device ID as a UTF-8 string and the remaining buffer space.
    /// - `Err(BufferOverflowError)`: The buffer was not large enough to hold the device ID.
    pub fn device_id<'b>(
        &'b self,
        buf: &'b mut [u8],
    ) -> Result<(&'b str, &'b mut [u8]), BufferOverflowError> {
        match self {
            DeviceCreds::PKI { pub_key } => Self::encode(pub_key, buf),
            DeviceCreds::Insecure { device_id } => Self::encode(device_id, buf),
        }
    }

    /// Get the public key bytes from the device credentials, if available.
    pub fn pub_key(&self) -> Option<&[u8]> {
        match self {
            DeviceCreds::PKI { pub_key } => Some(pub_key),
            DeviceCreds::Insecure { .. } => None,
        }
    }

    /// Encode the device ID as string into the provided buffer
    ///
    /// The string is guaranteed to contain only the following characters:
    /// - 'A'-'Z', 'a'-'z', '0'-'9', '+' and '-'
    fn encode<'a>(
        device_id: &[u8],
        buf: &'a mut [u8],
    ) -> Result<(&'a str, &'a mut [u8]), BufferOverflowError> {
        let (str, _) = base64::base64_encode(device_id, buf)?;

        let len = str.len();
        let (data, buf) = buf.split_at_mut(len);

        for byte in data.iter_mut() {
            if *byte == b'/' {
                *byte = b'-';
            }
        }

        Ok((unwrap!(core::str::from_utf8(data)), buf))
    }
}

bitflags! {
    /// Flags representing the operational networks supported by the device.
    #[repr(transparent)]
    #[derive(Default)]
    #[cfg_attr(not(feature = "defmt"), derive(Debug, Copy, Clone, Eq, PartialEq, Hash))]
    pub struct OpNetFlags: u8 {
        /// Ethernet network.
        const ETHERNET = 0x01;
        /// Wi-Fi network.
        const WIFI = 0x02;
        /// BLE network.
        const BLE = 0x04;
    }
}

/// The profile of the device, containing information about its capabilities and requirements.
///
/// This information is used by the onboarding installer to determine what data to generate
/// and send to the device in the onboarding bundle.
// TODO: Fill with data
#[derive(Copy, Clone, Debug)]
pub struct DeviceProfile<'a> {
    op_net_flags: OpNetFlags,
    /// For future compatibility, when lifetime parameters might be needed.
    _p: PhantomData<&'a ()>,
}

impl<'a> DeviceProfile<'a> {
    /// The maximum length of the serialized `DeviceProfile`.
    pub const MAX_SERIALIZED_LEN: usize = 1;

    /// Create a new `DeviceProfile` instance.
    pub const fn new(op_net_flags: OpNetFlags) -> Self {
        Self {
            op_net_flags,
            _p: PhantomData,
        }
    }

    /// Deserialize a `DeviceProfile` from the provided byte slice.
    ///
    /// # Arguments
    /// - `data`: A byte slice containing the serialized `DeviceProfile`.
    ///
    /// # Returns
    /// - `Ok(DeviceProfile)`: The deserialized `DeviceProfile`.
    /// - `Err(SerdeObjError)`: An error occurred during deserialization.
    pub fn deserialize(data: &'a [u8]) -> Result<Self, SerdeObjError> {
        if data.len() != 1 {
            return Err(SerdeObjError::InvalidData);
        }

        let op_net_flags = OpNetFlags::from_bits_truncate(data[0]);

        Ok(Self {
            op_net_flags,
            _p: PhantomData,
        })
    }

    /// Serialize the `DeviceProfile` into the provided buffer.
    ///
    /// # Arguments
    /// - `buf`: A mutable byte slice to write the serialized data into.
    ///
    /// # Returns
    /// - `Ok(&[u8])`: The serialized data as a byte slice.
    /// - `Err(SerdeObjError)`: An error occurred during serialization.
    pub fn serialize<'t>(
        &self,
        buf: &'t mut [u8],
    ) -> Result<(&'t [u8], &'t mut [u8]), SerdeObjError> {
        if buf.is_empty() {
            return Err(SerdeObjError::BufferOverflow);
        }

        buf[0] = self.op_net_flags.bits();

        let (device_profile, buf) = buf.split_at_mut(1);

        Ok((device_profile, buf))
    }
}

impl core::fmt::Display for DeviceProfile<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "DeviceProfile(op_net_flags={:?})", self.op_net_flags)
    }
}

#[cfg(feature = "defmt")]
impl defmt::Format for DeviceProfile<'_> {
    fn format(&self, fmt: defmt::Formatter) {
        defmt::write!(fmt, "DeviceProfile(op_net_flags={:?})", self.op_net_flags);
    }
}

/// The symmetric cryptographic key used for encrypting and decrypting the Onboarding protocol
/// once the public key exchange has been performed.
pub struct ChannelKey(Option<Key<Aes256Gcm>>);

impl ChannelKey {
    /// Return a reader wrapper that decrypts data read from the underlying reader.
    ///
    /// # Arguments
    /// - `buf`: A mutable buffer for temporary storage.
    ///
    /// # Returns
    /// - `(impl ReadWrapper, &'a mut [u8])`: A reader wrapper and the remaining buffer.
    pub fn read_wrapper<'a>(&self, buf: &'a mut [u8]) -> (impl ReadWrapper + 'a, &'a mut [u8]) {
        create_crypto_read_opt(self.0.as_ref(), buf)
    }

    /// Return a writer wrapper that encrypts data written to the underlying writer.
    ///
    /// # Arguments
    /// - `rng`: A cryptographic random number generator.
    /// - `buf`: A mutable buffer for temporary storage.
    ///
    /// # Returns
    /// - `(impl WriteWrapper, &'a mut [u8])`: A writer wrapper and the remaining buffer.
    pub fn write_wrapper<'a, C>(
        &self,
        rng: &'a mut C,
        buf: &'a mut [u8],
    ) -> (impl WriteWrapper + 'a, &'a mut [u8])
    where
        C: RngCore,
    {
        create_crypto_write_opt(self.0.as_ref(), rng, buf)
    }
}

/// Metadata about the installer itself.
///
/// Generated and published by the installer, and consumed by the device.
/// Corresponds to the `InstallerMeta` message of the Onboarding protocol.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct InstallerMeta<'a> {
    /// The _ephemeral_ EC NistP526 public key of the installer, in a BASE64-encoded format.
    ///
    /// Necessary so as to establish an encrypted and authenticated channel between
    /// the installer and the device.
    dh_installer_pub_key: Option<&'a str>,
}

impl<'a> SerdeObj<'a> for InstallerMeta<'a> {
    /// The maximum size of the serialized `InstallerMeta`, as JSON.
    const MAX_BUF_SIZE: usize = 150;
}

/// Status information about the onboarding process.
///
/// Generated and published by the device, and consumed by the installer
/// so that the installer can track the progress of the onboarding process.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct OnboardingStatus<'a> {
    /// A human-readable status message.
    status: &'a str,
    /// Whether the onboarding process is done.
    done: bool,
}

impl<'a> SerdeObj<'a> for OnboardingStatus<'a> {
    /// The maximum size of the serialized `OnboardingStatus`, as JSON.
    const MAX_BUF_SIZE: usize = 100;
}

/// Errors that can occur during the onboarding process of the device.
#[derive(Error, Debug, Copy, Clone, Eq, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum DeviceError<P, C> {
    /// The onboarding bundle metadata is invalid.
    #[error("invalid installer meta-data")]
    InvalidInstallerMeta,
    /// A buffer overflow occurred.
    #[error("buffer overflow")]
    BufferOverflow(#[from] BufferOverflowError),
    /// A format buffer overflow occurred.
    #[error("buffer overflow: {0}")]
    FormatBufferOverlfow(#[from] core::fmt::Error),
    /// A serialization/deserialization error occurred.
    #[error("serde error: {0}")]
    Serde(#[from] SerdeObjError),
    /// An I/O error occurred.
    #[error("IO error: {0:?}")]
    Io(ErrorKind),
    /// An error occured when producing the DeviceAttestation message stream.
    #[error("attestation error: {0:?}")]
    Attestation(P),
    /// An error occured when consuming the OnboardingData message stream.
    #[error("obboarding data error: {0:?}")]
    Data(C),
}

impl<P, C> DeviceError<P, C> {
    /// Create a new `DeviceError` from an I/O error.
    pub fn io<E: embedded_io_async::Error>(error: E) -> Self {
        Self::Io(error.kind())
    }
}

impl<P, C> From<ErrorKind> for DeviceError<P, C> {
    fn from(kind: ErrorKind) -> Self {
        Self::Io(kind)
    }
}

/// Errors that can occur during the onboarding process driven by the installer.
#[derive(Error, Debug, Copy, Clone, Eq, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum InstallerError<C, P> {
    /// The device credentials are invalid.
    #[error("invalid device credentials")]
    InvalidDeviceCreds,
    /// The device sent an invalid status update.
    #[error("invalid device status")]
    InvalidDeviceStatus,
    /// A buffer overflow occurred.
    #[error("buffer overflow")]
    BufferOverflow(#[from] BufferOverflowError),
    /// A format buffer overflow occurred.
    #[error("buffer overflow: {0}")]
    FormatBufferOverlfow(#[from] core::fmt::Error),
    /// A serialization/deserialization error occurred.
    #[error("serde error: {0}")]
    Serde(#[from] SerdeObjError),
    /// An I/O error occurred.
    #[error("IO error: {0:?}")]
    Io(ErrorKind),
    /// An error occured when consuming the DeviceAttestation message stream.
    #[error("attestation error: {0:?}")]
    Attestation(C),
    /// An error occured when producing the OnboardingData message stream.
    #[error("obboarding data error: {0:?}")]
    Data(P),
}

impl<C, P> InstallerError<C, P> {
    /// Create a new `InstallerError::Io` from an I/O error.
    pub fn io<E: embedded_io_async::Error>(error: E) -> Self {
        Self::Io(error.kind())
    }
}

impl<C, P> From<ErrorKind> for InstallerError<C, P> {
    fn from(kind: ErrorKind) -> Self {
        Self::Io(kind)
    }
}
