[package]
name = "introspection-common"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
zenoh = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
serde_with = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }

[lints]
workspace = true
