[package]
name = "sorg-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[features]
default = []

[dependencies]
tokio = { workspace = true }

zenoh = { workspace = true, features = ["transport_tls"] }
rustls = { workspace = true, features = ["ring"] }
zenoh_backend_traits = { workspace = true }
swarm = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
claims = { workspace = true }

cell-protocol = { workspace = true, default-features = true }
myrmic-tags = { workspace = true }
sorg-common = { workspace = true }
introspection-common = { workspace = true }
sorg-client = { workspace = true }
rumqttd = { workspace = true }
rumqttc = { workspace = true }
config = { workspace = true }

uuid = { workspace = true, features = ["std"] }
myrmic-common = { workspace = true }
myrmic-build = { workspace = true }
futures = { workspace = true }
tokio-stream = { workspace = true, features = ["sync"] }

db-client = { workspace = true, features = ["zenoh"] }
filestore-client = { workspace = true }
serde = { workspace = true }
postcard = { workspace = true }

log = { workspace = true }
env_logger = { workspace = true }
wiremock = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
zenoh = { workspace = true, default-features = true }
