#!/bin/bash

# Runs a command inside the ESP-IDF Docker container.
# Usage: run-in-docker <command> [args...]
#
# Environment variables (all optional, forwarded to the container when set):
#   BLE_MAC, SSID, SSID_PWD, MQTT_URL, MQTT_CLIENT_ID, MQTT_SUB_TOPIC, MQTT_PUB_TOPIC

set -eu

SCRIPT_DIR="$(readlink -f "$(dirname "$0")")"
REPO_ROOT="$(readlink -f "$SCRIPT_DIR/../")"

PURPLE='\033[0;35m'
NC='\033[0m' # No Color

IMAGE="${IMAGE:-ghcr.io/peeriot/rust-riscv32imac-esp-espidf:1.91.1-idf-v5.5.1}"

echo -e "${PURPLE}###   Running script in docker...${NC}"
docker pull "${IMAGE}" || true

# Exclude .git file/folder from the mount
if [ -d "${REPO_ROOT}/.git" ]; then
    hide_git_arg="--mount type=tmpfs,destination=/code/.git"
else
    hide_git_arg="-v /dev/null:/code/.git"
fi

ssh_detected=""
[[ -d "$HOME/.ssh" ]] && ssh_detected=true

# Forward optional environment variables when they are set
env_args=()
for var in BLE_MAC SSID SSID_PWD MQTT_URL MQTT_CLIENT_ID MQTT_SUB_TOPIC MQTT_PUB_TOPIC; do
    eval "val=\${$var:-}"
    if [ -n "$val" ]; then
        env_args+=(--env "${var}=${val}")
    fi
done

docker run \
    --rm \
    -it \
    -v "${REPO_ROOT}":/code \
    $hide_git_arg \
    ${ssh_detected:+-v "$HOME"/.ssh:/home/dev/.ssh} \
    -v "$HOME"/.cargo/git:/usr/local/cargo/git \
    -v "$HOME"/.cargo/registry:/usr/local/cargo/registry \
    --env HOST_GID="$(id -g)" \
    --env HOST_UID="$(id -u)" \
    --env DOCKER_ENV=1 \
    --env CARGO_NET_GIT_FETCH_WITH_CLI=true \
    "${env_args[@]+"${env_args[@]}"}" \
    -w /code \
    "${IMAGE}" \
    "$@"
