[package]
name = "introspection-client"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
thiserror = { workspace = true }

zenoh = { workspace = true }

introspection-common = { workspace = true }
serde_json = { workspace = true, features = ["std"] }
anyhow = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]

tokio = { workspace = true, features = ["macros"] }
sorg-tests = { workspace = true }
claims = { workspace = true }

[lints]
workspace = true
