[package]
name = "test-framework"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
axum = { workspace = true }
bollard = { workspace = true }
bytes = { workspace = true }
config = { workspace = true }
rumqttc = { workspace = true }
rumqttd = { workspace = true }
cell-protocol = { workspace = true, default-features = true }
claims = { workspace = true }
db-client = { workspace = true, features = ["zenoh"] }
futures = { workspace = true }
introspection-client = { workspace = true }
introspection-common = { workspace = true }
postcard = { workspace = true }
rand = { workspace = true }
reqwest = { version = "0.13.3", features = ["query", "json"] }
serde = { workspace = true }
serde_json = { workspace = true }
sorg-client = { workspace = true }
sorg-common = { workspace = true }
swarm = { workspace = true }
swarm-telemetry = { workspace = true, features = ["export-db", "export-file"] }
tar = { workspace = true }
tempfile = { workspace = true }
test-control-client = { workspace = true }
test-control-common = { workspace = true }
tryhard = { workspace = true }
tokio = { workspace = true, features = ["process", "net", "time", "sync", "rt"] }
uuid = { workspace = true, features = ["v4"] }
zenoh = { workspace = true, features = ["transport_tcp", "unstable"] }

[lints]
workspace = true
