"""Generate the driver and step reference pages from the module descriptors."""
import yaml, glob, os, textwrap

class Loader(yaml.SafeLoader):
    """YAML 1.1 turns bare Off/On/Yes/No into booleans; the Rust side (serde)
    does not, so a descriptor's `default: Off` means the enum variant. Restrict
    bool parsing to true/false so the catalogue prints what codegen sees."""

import re as _re
Loader.yaml_implicit_resolvers = {
    k: [(tag, regexp) for tag, regexp in v if tag != "tag:yaml.org,2002:bool"]
    for k, v in yaml.SafeLoader.yaml_implicit_resolvers.items()
}
Loader.add_implicit_resolver(
    "tag:yaml.org,2002:bool", _re.compile(r"^(?:true|false)$"), list("tf"))

OUT = "doc/chapters/10_reference/04_signal-layer"
# MDX compiles an HTML comment into a JS block comment, so the text must not
# contain "*/" -- a glob like signal-modules/*/*/descriptor.yaml closes it early
# and the rest of the page is parsed as JavaScript.
BANNER = ("<!-- Generated by doc/tools/gen-signal-layer-reference.py from the "
          "signal-modules descriptors. Edit the descriptors, not this page. -->\n\n")

def load(kind):
    mods = []
    for d in sorted(glob.glob(f"signal-modules/{kind}/*/")):
        f = os.path.join(d, "descriptor.yaml")
        if not os.path.exists(f): continue
        y = yaml.load(open(f), Loader=Loader) or {}
        y["_dir"] = os.path.basename(d.rstrip("/"))
        mods.append(y)
    return mods

def wrap(t, width=94):
    """Hard-wrap for source readability only; markdown rejoins the lines with a space.

    break_on_hyphens would split "Re-entering" across lines and render it as "Re- entering",
    and break_long_words would split a long `code span` mid-token.
    """
    if not t: return ""
    return "\n".join(textwrap.wrap(" ".join(t.split()), width,
                                   break_on_hyphens=False, break_long_words=False))

def yamlish(v):
    """Render a default the way it is written in YAML, not the way Python repr()s it."""
    if v is True: return "`true`"
    if v is False: return "`false`"
    if v is None: return "-"
    return f"`{v}`"

def cfg_table(schema):
    if not schema: return "_No configuration._\n"
    rows = ["| Field | Where it is set | Type | Default |", "|---|---|---|---|"]
    for k, v in schema.items():
        v = v or {}
        scope = v.get("scope", "application")
        where = "board file" if scope == "hardware" else "pipeline"
        rows.append(f"| `{k}` | {where} | `{v.get('rust_type','-')}` | "
                    f"{yamlish(v.get('default'))} |")
    return "\n".join(rows) + "\n"

# ---- drivers ---------------------------------------------------------------
drivers = load("drivers")
sensors = [d for d in drivers if d.get("outputs") and not d.get("writes")]
actuators = [d for d in drivers if d.get("writes")]

lines = ["# Drivers\n", BANNER,
 "A driver is what knows one device. A board file names a driver on a device; a pipeline then\n"
 "reads that device as a source or writes to it through an outlet.\n\n"
 f"There are {len(drivers)} drivers in the tree. A device's `driver:` value is the directory name\n"
 "below, and the crate it resolves to is that name plus `-driver`.\n"]

lines.append("\n## Sensor drivers\n\nThese produce values a pipeline can tap.\n")
lines.append("\n| Driver | Reads over | Publishes | Extra pins |\n|---|---|---|---|")
for d in sensors:
    outs = ", ".join(f"`{o['name']}` ({o.get('type','?')}{', '+o['unit'] if o.get('unit') else ''})"
                     for o in d.get("outputs", []))
    buses = ", ".join(b["transport"].upper() for b in (d.get("requires") or {}).get("buses", [])) or "-"
    pins = ", ".join(f"`{p}`" for p in (d.get("requires") or {}).get("optional_pins", [])) or "-"
    lines.append(f"| `{d['_dir']}` | {buses} | {outs} | {pins} |")

lines.append("\n## Output drivers\n\nThese consume a command written to an outlet.\n")
lines.append("\n| Driver | Command | Mode | Pins | Reports back |\n|---|---|---|---|---|")
for d in actuators:
    w = d.get("writes") or {}
    pins = ", ".join(f"`{p}`" for p in (d.get("requires") or {}).get("optional_pins", [])) or "-"
    back = ", ".join(f"`{o['name']}`" for o in d.get("outputs", [])) or "nothing"
    lines.append(f"| `{d['_dir']}` | `{w.get('type','?')}` | {w.get('mode','?')} | {pins} | {back} |")

lines.append("\n## Each driver in detail\n")
for d in drivers:
    lines.append(f"\n### `{d['_dir']}`\n")
    if d.get("description"): lines.append(wrap(d["description"]) + "\n")
    req = d.get("requires") or {}
    bits = []
    if req.get("buses"): bits.append("bus: " + ", ".join(b["transport"].upper() for b in req["buses"]))
    if req.get("optional_pins"): bits.append("pins: " + ", ".join(f"`{p}`" for p in req["optional_pins"]))
    if bits: lines.append("\n**Requires** - " + "; ".join(bits) + "\n")
    if d.get("outputs"):
        lines.append("\n**Publishes**\n")
        lines.append("\n| Name | Type | Unit |\n|---|---|---|")
        for o in d["outputs"]:
            lines.append(f"| `{o['name']}` | `{o.get('type','?')}` | {o.get('unit') or '-'} |")
    if d.get("writes"):
        w = d["writes"]
        lines.append(f"\n**Accepts** - `{w.get('type')}` in `{w.get('mode')}` mode\n")
    lines.append("\n**Configuration**\n")
    lines.append(cfg_table(d.get("config_schema")))
open(f"{OUT}/03_drivers.md", "w").write("\n".join(lines) + "\n")

# ---- steps -----------------------------------------------------------------
steps = load("steps")
lines = ["# Steps\n", BANNER,
 "A step transforms a value on its way through a pipeline. A pipeline names one with `op:`,\n"
 "which is both the directory below and the crate name, with no suffix.\n\n"
 f"There are {len(steps)} steps in the tree.\n"]
lines.append("\n| Step | Takes | Produces | Configuration |\n|---|---|---|---|")
for s in steps:
    i = ", ".join(f"`{x.get('type','?')}`" for x in s.get("inputs", [])) or "any"
    o = ", ".join(f"`{x.get('type','?')}`" for x in s.get("outputs", [])) or "same as input"
    c = ", ".join(f"`{k}`" for k in (s.get("config_schema") or {})) or "-"
    lines.append(f"| `{s['_dir']}` | {i} | {o} | {c} |")
lines.append("\n## Each step in detail\n")
for s in steps:
    lines.append(f"\n### `{s['_dir']}`\n")
    if s.get("description"): lines.append(wrap(s["description"]) + "\n")
    else: lines.append("_No description in the descriptor._\n")
    i = s.get("inputs") or []; o = s.get("outputs") or []
    if i or o:
        lines.append("\n| | Name | Type |\n|---|---|---|")
        for x in i: lines.append(f"| in | `{x['name']}` | `{x.get('type','?')}` |")
        for x in o: lines.append(f"| out | `{x['name']}` | `{x.get('type','?')}` |")
        lines.append("")
    else:
        lines.append("\nType-transparent: it declares no fixed input or output type and passes through\n"
                     "whatever it carries.\n")
    lines.append("\n**Configuration**\n")
    lines.append(cfg_table(s.get("config_schema")))
open(f"{OUT}/04_steps.md", "w").write("\n".join(lines) + "\n")
print(f"  drivers page: {len(drivers)} modules   steps page: {len(steps)} modules")
