[package]
name = "skey"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[features]
default = ["derive", "serde"]
derive = ["dep:skey-macros"]
serde = ["dep:serde", "dep:generic-array"]

[dependencies]
anyhow = { workspace = true }
byteorder = { workspace = true }
thiserror = { workspace = true }
skey-macros = { workspace = true, optional = true }
memchr = { workspace = true }
uhlc = { workspace = true }
serde = { workspace = true, optional = true }
generic-array = { version = "1.2.0", optional = true, features = ["serde"] }
