[package]
name = "cell-counter-logic"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.myrmic]
heap_size = 65_536

[lib]
crate-type = ["rlib"]

[lints]
workspace = true

[dependencies]
myrmic-sdk = { workspace = true }

serde = { workspace = true }
