[target.wasm32-unknown-unknown]
rustflags = [
    "-C",
    "link-arg=-zstack-size=32768",
    "-C",
    "link-arg=--stack-first",
    "-C",
    "link-arg=--initial-memory=131072",
    "-C",
    "link-arg=--max-memory=131072",
    "-C",
    "target-cpu=mvp",
]

[alias]
citest = "nextest run"
