[package]
name = "tier_1_object"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.myrmic]
heap_size = 8_000

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
myrmic-sdk = { workspace = true, features = ["cells", "cell-init"] }

serde = { workspace = true }
