[package]
name = "sorg-orchestration"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true }
uuid = { workspace = true, features = ["std", "v4"] }
serde = { workspace = true, features = ["derive"] }

zenoh = { workspace = true, features = ["unstable"] }

cell-protocol = { workspace = true, default-features = true }
flume = { workspace = true }
sorg-common = { path = "../sorg-common" }
sorg-execution = { path = "../sorg-execution" }
introspection-client = { path = "../introspection-client" }
futures = { workspace = true }
tryhard = { workspace = true }
topo_sort = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }
zenoh = { workspace = true, features = ["unstable", "default"] }
claims = { workspace = true }
postcard = { workspace = true }
zenoh-protocol = { workspace = true }
serde_json = { workspace = true }
sorg-client = { path = "../sorg-client" }
filestore-client = { path = "../filestore-client" }
sorg-tests = { path = "../sorg-tests" }
module-examples-common = { path = "../../tests/fixtures/module-examples-common" }

[lints]
workspace = true
