[package]
name = "cell-wdt-selftest-logic"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["rlib"]

[lints]
workspace = true

[dependencies]
myrmic-sdk = { workspace = true }

postcard = { workspace = true }
serde = { workspace = true }
