#!/usr/bin/env bash
# Cargo `runner` wrapper for flashing ESP32 firmware.
#
# Cargo invokes this as `<runner> <path-to-binary> [binary-args...]`. We locate the app partition table generated by
# `modem-esp32`'s build.rs (in its build-script $OUT_DIR, next to the built binary) and pass it to espflash via
# `--partition-table`, so the firmware ceiling is enforced at flash time. If no generated table is found (e.g. a
# different riscv binary, or modem-esp32 hasn't been built with a build script), we fall back to a plain flash so this
# stays safe as the shared riscv runner.
set -euo pipefail

bin="$1"
shift

csv=""
build_dir="$(dirname "$bin")/build"
if [ -d "$build_dir" ]; then
    # Newest matching table wins (the current build just wrote it).
    csv="$(ls -t "$build_dir"/modem-esp32-*/out/partitions.generated.csv 2>/dev/null | head -n1 || true)"
fi

if [ -n "$csv" ]; then
    echo "espflash-runner: using partition table $csv" >&2
    exec espflash flash --monitor --partition-table "$csv" "$bin" "$@"
else
    echo "espflash-runner: no generated partition table found; flashing with espflash defaults" >&2
    exec espflash flash --monitor "$bin" "$@"
fi
